TASK_SPECS = {
    "safe": {
        "type": "take",
        "bg": "sprites/safe_task.png",
        "question": "Выберите цифру:",
        "options": ["1. Взять яблоко", "2. Вернуться"],
        "required": ["код от сейфа"],
        "add_items": ["ЯБЛОКО"],
        "remove_items": ["код от сейфа"],
        "feedback": {"success": "Вы взяли ЯБЛОКО!", "fail": "У вас нет кода!"},
    },
    "cabinet": {
        "type": "quiz",
        "bg": "sprites/cabinet_task.png",
        "question": "Выберите цифру правильного варианта ответа:",
        "options": ["1. 31", "2. 1", "3. 9", "4. 16"],
        "correct": 4,
        "add_items": ["ключ"],
        "feedback": {"success": "ВЕРНО!", "fail": "НЕВЕРНО!"},
    },
    "letter": {
        "type": "note",
        "bg": "sprites/letter_task.png",
        "question": "Выберите цифру:",
        "options": ["1. Вернуться"],
        "feedback": {"success": "", "fail": ""},
    },
    "bake": {
        "type": "take",
        "bg": "sprites/bake_task.png",
        "question": "Выберите цифру:",
        "options": ["1. Взять муку", "2. Вернуться"],
        "required": [],
        "add_items": ["мука"],
        "remove_items": [],
        "feedback": {"success": "Вы взяли муку!", "fail": ""},
    },
    "fridge": {
        "type": "take",
        "bg": "sprites/fridge_task.png",
        "question": "Выберите цифру:",
        "options": ["1. Взять молоко", "2. Вернуться"],
        "required": ["ключ"],
        "add_items": ["молоко"],
        "remove_items": ["ключ"],
        "feedback": {"success": "Вы взяли молоко!", "fail": "У вас нет ключа!"},
    },
    "painting": {
        "type": "quiz",
        "bg": "sprites/painting_task.png",
        "question": "Выберите цифру правильного варианта ответа:",
        "options": ["1. Чёрный куб", "2. Белый параллелограм", "3. Чёрный квадрат", "4. Чёрный прямоугольник"],
        "correct": 3,
        "add_items": ["яйца"],
        "feedback": {"success": "ВЕРНО!", "fail": "НЕВЕРНО!"},
    },
    "exit": {
        "type": "take",
        "bg": "sprites/exit_task.png",
        "question": "Выберите цифру:",
        "options": ["1. Хочу выбраться", "2. Вернуться"],
        "required": ["отпечаток", "ЯБЛОКО"],
        "add_items": ["КОНЕЦ"],
        "remove_items": ["отпечаток", "ЯБЛОКО"],
        "feedback": {"success": "ВЫ ВЫШЛИ! Mission completed. Respect +", "fail": "У вас нет отпечатка или яблока!"},
    },
    "table": {
        "type": "quiz",
        "bg": "sprites/table_task.png",
        "question": "Выберите цифру правильного варианта ответа:",
        "options": ["1. Тишина", "2. Воздух", "3. Время", "4. Друг"],
        "correct": 1,
        "add_items": ["МЕЧ"],
        "feedback": {"success": "ВЕРНО!", "fail": "НЕВЕРНО!"},
    },
    "finish": {
        "type": "ending",
        "bg": None,
        "message": "Спасибо, что прошёл мою игру))",
        "options": [],
    },
}